### ISSUE TITLE
dyn_model not iterating through all temperatures

### ISSUE THREAD

**Issue by vallettea** [batterysim/esctoolbox-python#1]
Hello, thanks for this work which I much appreciated since I don"t have matlab and I can't run Plett's code.
I've run your code and it seems all the difficult stuff works perfectly. However at the end of `dyn_model.py` the object `modelDyn` seems incomplete as only the first values of RCParam, RParam etc is not null.

Am I missing something or didn't you have time to finish ?

**Comment by wigging** [comment]
I haven't completed the dynamic model of the toolbox. I had plans to use the esctoolbox for a research project but I ultimately decided to take a different approach which is why I didn't complete the dynamic portion. If you think you will use the Python version, I can make some time to complete it.

**Comment by vallettea** [comment]
thanks for your answer.
It seems there is not a lot of work to have something finished but if you don't have time I'll understand.
best,
