### ISSUE TITLE
Dynamical Data Script Splitting 

### ISSUE THREAD

**Issue by salehmsaddi** [batterysim/esctoolbox-python#4]
The dynamic data per cell/temperature found in the MATLAB toolbox are composed of 2 Excel files (s1 and s2) while the one in the Python toolbox reads 3 CSV files (s1, s2 and s3). 

How did you spit s2 into two files to use them in the Python script?

**Comment by wigging** [comment]
The CSV files are created from the `.mat` files in the original Matlab toolbox. Not from the Excel files. In the `.mat` files you will see data related to scripts 1, 2, and 3 which are related to the CSV files labeled with s1, s2, and s3.

**Comment by salehmsaddi** [comment]
Thank you for the explanation. 
Is it possible that you share the function that you used to convert the .mat files to CSV?

**Comment by wigging** [comment]
I think I saved it to CSV using Matlab. SciPy also has functions for reading Matlab .mat files which can then be saved to CSV.

**Comment by wigging** [comment]
@salehmsaddi Can you close this issue if you don't have any more questions?
